### PR TITLE
First pass at adding kubernetes templates

### PR DESCRIPTION
**Pull request by chelseatroy**
Added kubernetes templates similar to the example in tove.

Next I am going to set up the secrets (if I can), starting with some research and the page you sent. 

I haven't tried out these templates or anything yet: I am in the process of setting up kubernetes on my machine at the moment. I went with all the same settings tove has basically, but these might need to be changed?

### CODE REVIEW

**Comment by zwolf** [comment]
This PR is dependent on the Docker image being complete and functional. The [Jenkins console log](https://jenkins.zooniverse.org/job/Zooniverse%20GitHub/job/theia/job/PR-101/3/consoleFull) that's causing the failing check is having trouble with some part of the python install when it builds the container. This looks kinda familiar (I struggled to get this building locally) but the prior PR that updated the Dockerfile seemed to help. Perhaps this just needs a rebase, though I'm not sure why Github's not complaining about it being out of date.

**Comment by camallen** [comment]
> This PR is dependent on the Docker image being complete and functional. The [Jenkins console log](https://jenkins.zooniverse.org/job/Zooniverse%20GitHub/job/theia/job/PR-101/3/consoleFull) that's causing the failing check is having trouble with some part of the python install when it builds the container. This looks kinda familiar (I struggled to get this building locally) but the prior PR that updated the Dockerfile seemed to help. Perhaps this just needs a rebase, though I'm not sure why Github's not complaining about it being out of date.

FWIW I don't think the PR to fix the docker build https://github.com/zooniverse/theia/pull/96 was merged to the container branch before that branch was merged to master. So in essence the PR commits / merge commit on #96 are missing on the master branch

**Comment by zwolf** [comment]
Ah, I see. That PR wasn't into master, and since the deployment templates rely on that branch being what you want to deploy, that'll have to be updated first. Should be able to do a quick merge n' push for master, then this PR will let you do a merge commit.

**Comment by chelseatroy** [comment]
Oh, I see. I scrolled right past the top of PR 96 when I read it and thought it was into master. My bad! I'll go back and rebase this branch off of the `containerize` branch and we should be good to go.

**Pull request merged**
